[workspace]
members = ["crates/xtask", "crates/fixture-server", "crates/dezoomify-core", "crates/dezoomify-protocol", "crates/dezoomify-job", "crates/dezoomify-wasm", "crates/dezoomify-native", "apps/cli"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/lovasoa/dezoomify-ng"
