#[cfg(feature = "tauri")]
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/desktop_commands.rs"));

fn main() {
    println!("cargo:rerun-if-changed=tauri.conf.json");
    println!("cargo:rerun-if-changed=capabilities/generated.json");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=desktop_commands.rs");
    // The real window shell needs the Tauri build step to resolve
    // capabilities and embed assets; the lean shell keeps the offline stub.
    #[cfg(feature = "tauri")]
    {
        // Desktop commands are registered as an inlined plugin so
        // the generated capability document's `dezoomify:allow-*` entries
        // resolve to real autogenerated permissions.
        macro_rules! command_names {
            ($($command:ident),* $(,)?) => { &[$(stringify!($command)),*] };
        }
        const COMMANDS: &[&str] = desktop_commands!(command_names);
        let attributes = tauri_build::Attributes::new().plugin(
            "dezoomify",
            tauri_build::InlinedPlugin::new().commands(COMMANDS),
        );
        tauri_build::try_build(attributes).expect("failed to run the Tauri build step");
    }
}
