fn main() {
    println!("cargo:rerun-if-changed=tauri.conf.json");
    println!("cargo:rerun-if-changed=capabilities/generated.json");
    println!("cargo:rerun-if-changed=build.rs");
    // The real window shell needs the Tauri build step to resolve
    // capabilities and embed assets; the lean shell keeps the offline stub.
    #[cfg(feature = "tauri")]
    {
        // The five desktop commands are registered as an inlined plugin so
        // the generated capability document's `dezoomify:allow-*` entries
        // resolve to real autogenerated permissions.
        const COMMANDS: &[&str] = &[
            "start_job",
            "cancel_job",
            "answer_choice",
            "request_destination",
            "query_capabilities",
        ];
        let attributes = tauri_build::Attributes::new().plugin(
            "dezoomify",
            tauri_build::InlinedPlugin::new().commands(COMMANDS),
        );
        tauri_build::try_build(attributes).expect("failed to run the Tauri build step");
    }
}
