[package]
name = "dezoomify-fixture-server"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "dezoomify-fixture-server"
path = "src/main.rs"

[lib]
name = "dezoomify_fixture_server"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio = { workspace = true, features = ["macros", "io-util", "sync", "time", "fs"] }
serde.workspace = true
serde_json.workspace = true
hmac.workspace = true
sha1.workspace = true
aes.workspace = true
cbc.workspace = true
base64.workspace = true
regex.workspace = true

[dev-dependencies]
reqwest.workspace = true
