[[target]]
name = "cli-linux-x86_64"
os = "linux"

[[target]]
name = "desktop-linux-x86_64"
os = "linux"

[[target]]
name = "desktop-windows-x86_64"
os = "windows"

[[target]]
name = "desktop-macos-aarch64"
os = "macos"

[[target]]
name = "extension-chromium"
os = "any"

[[target]]
name = "extension-firefox"
os = "any"
