import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

// Extension shared-UI parity (todo 2.1): the no-bundler page renders through
// build-time vendor codegen (`src/page/vendor/`, generated by
// scripts/sync-web-js.mjs). These gates fail when the page drifts from the
// canonical shared-ui sources: mirrors must be byte-identical, the page must
// link the vendored theme with no inline fork, every `dz-*` class the page
// touches must exist in the canonical theme (web vs extension job cards
// cannot visually diverge), static shell ids must not collide with
// renderView-managed ids, and the rendered job/completed cards must carry
// the website geometry. Regenerate vendor with
// `node scripts/sync-web-js.mjs` (`cargo xtask test extension` does this
// before the unit glob); never hand-edit vendor/.

function read(rel) {
  return readFileSync(new URL(rel, import.meta.url), "utf8");
}

const VENDOR_JS = [
  ["../../src/page/vendor/controller.js", "../../../../packages/shared-ui/src/controller.js"],
  ["../../src/page/vendor/view.js", "../../../../packages/shared-ui/src/view.js"],
  ["../../src/page/vendor/components.js", "../../../../packages/shared-ui/src/components.js"],
  ["../../src/page/vendor/history.js", "../../../../packages/shared-ui/src/history.js"],
  ["../../src/page/vendor/saveName.js", "../../../../packages/shared-ui/src/saveName.js"],
  ["../../src/page/vendor/i18n.js", "../../../../packages/shared-ui/src/i18n.js"],
  ["../../src/page/vendor/locales/fr.js", "../../../../packages/shared-ui/src/locales/fr.js"],
  ["../../src/page/vendor/locales/de.js", "../../../../packages/shared-ui/src/locales/de.js"],
  ["../../src/page/vendor/locales/it.js", "../../../../packages/shared-ui/src/locales/it.js"],
  ["../../src/page/vendor/limits.js", "../../../../packages/browser-runtime/src/limits.js"],
  ["../../src/page/vendor/transport-labels.js", "../../../../packages/browser-runtime/src/transport-labels.js"],
  ["../../src/page/vendor/save-name.js", "../../../../packages/browser-runtime/src/save-name.js"],
  ["../../src/page/vendor/crop.js", "../../../../packages/browser-runtime/src/crop.js"],
];

test("vendor mirrors carry the canonical logic (flattened for no-bundler)", () => {
  // Same type-strip as the website mirrors, plus the vendor flattening from
  // scripts/sync-web-js.mjs: canonical cross-package re-exports
  // (`../../browser-runtime/src/X.js`) land side by side with their
  // importers, so they become `./X.js`.
  const flatten = (source) => source.replaceAll('"../../browser-runtime/src/', '"./');
  for (const [vendorRel, canonRel] of VENDOR_JS) {
    assert.equal(read(vendorRel), flatten(read(canonRel)), `${vendorRel} must equal its canonical mirror`);
  }
  assert.equal(
    read("../../src/page/vendor/theme.css"),
    read("../../../../packages/shared-ui/src/styles/theme.css"),
    "vendor theme must equal the canonical theme",
  );
});

test("vendor graph is self-contained (no bundler, no outside imports)", () => {
  for (const [vendorRel] of VENDOR_JS) {
    const source = read(vendorRel);
    for (const match of source.matchAll(/from\s+["']([^"']+)["']/g)) {
      assert.match(match[1], /^\.\//, `${vendorRel} must only import vendored siblings (saw ${match[1]})`);
    }
  }
});

test("page links the vendored theme with no inline theme fork", () => {
  const html = read("../../src/page/page.html");
  assert.ok(html.includes('<link rel="stylesheet" href="vendor/theme.css" />'), "page must link the vendored canonical theme");
  const styles = [...html.matchAll(/<style>([\s\S]*?)<\/style>/g)].map((m) => m[1]).join("\n");
  assert.ok(!styles.includes(".dz-"), "page chrome style must define no dz-* geometry (theme owns it)");
});

test("every dz-* class the page touches exists in the canonical theme", () => {
  const theme = read("../../src/page/vendor/theme.css");
  const html = read("../../src/page/page.html");
  const page = read("../../src/page/page.ts");
  const classes = new Set();
  // class="..." attributes (shell markup) and className assignments plus
  // class selectors (page augmentation slots). Id selectors (`#dz-...`)
  // are deliberately skipped: they are mount points, not styled geometry.
  for (const m of html.matchAll(/class="([^"]*)"/g)) {
    for (const token of m[1].split(/\s+/)) {
      if (token.startsWith("dz-")) classes.add(token);
    }
  }
  for (const m of page.matchAll(/className\s*=\s*"([^"]*)"/g)) {
    for (const token of m[1].split(/\s+/)) {
      if (token.startsWith("dz-")) classes.add(token);
    }
  }
  for (const m of page.matchAll(/querySelector\("([^"]+)"\)/g)) {
    for (const token of m[1].split(/[\s.]+/)) {
      if (token.startsWith("dz-")) classes.add(token);
    }
  }
  assert.ok(classes.size > 5, `page touches shared geometry (saw ${classes.size} classes)`);
  const missing = [...classes].filter((cls) => !new RegExp(`\\.${cls}(?![\\w-])`).test(theme));
  assert.deepEqual(missing, [], `page uses theme-unknown classes (visual drift): ${missing.join(", ")}`);
});

test("static shell ids never collide with renderView-managed ids", () => {
  const html = read("../../src/page/page.html");
  const vendorView = read("../../src/page/vendor/view.js");
  const shellIds = new Set([...html.matchAll(/id="([^"]+)"/g)].map((m) => m[1]));
  const managedIds = new Set([...vendorView.matchAll(/id="([^"]+)"/g)].map((m) => m[1]));
  const clash = [...shellIds].filter((id) => managedIds.has(id));
  assert.deepEqual(clash, [], `shell ids collide with renderView ids: ${clash.join(", ")}`);
});

test("page routes every effect through the live extension integration", () => {
  // v1 page drives the guarded session fetcher directly (see
  // src/app/extensionIntegration.ts status note); integration wiring lands
  // when the page adopts the shared UI. This gate pins the v1 reality plus
  // the integration contract so the migration stays detectable.
  const page = readFileSync(new URL("../../src/page/page.ts", import.meta.url), "utf8");
  assert.ok(
    page.includes("createSessionFetcher") || page.includes("createExtensionIntegration"),
    "page must drive effects through the session fetcher (v1) or the extension integration (shared-UI migration)",
  );
  const integration = readFileSync(
    new URL("../../src/app/extensionIntegration.ts", import.meta.url),
    "utf8",
  );
  for (const kind of ["StartScan", "FetchResource", "StartNativeHandoff"]) {
    assert.ok(integration.includes(kind), `integration must route ${kind}`);
  }
});

// --- minimal mock DOM for the rendered-card smoke below ---

function createMockElement(tagName, ownerDocument) {
  const attrs = new Map();
  const children = [];
  const classes = new Set();
  const listeners = new Map();
  const el = {
    tagName: String(tagName).toUpperCase(),
    ownerDocument,
    style: {},
    dataset: {},
    title: "",
    parentNode: null,
    children,
    get classList() {
      return {
        add(...cls) { cls.forEach((c) => classes.add(c)); },
        remove(...cls) { cls.forEach((c) => classes.delete(c)); },
        contains(c) { return classes.has(c); },
      };
    },
    get className() { return [...classes].join(" "); },
    set className(val) {
      classes.clear();
      String(val || "").split(/\s+/).filter(Boolean).forEach((c) => classes.add(c));
    },
    _id: "",
    get id() { return el._id; },
    set id(val) { el._id = String(val || ""); },
    _text: "",
    get textContent() {
      // Direct text plus descendant text (e.g. a header holding an icon
      // plus its label): either source alone can carry the name.
      const kids = children.map((c) => c.textContent).join("");
      return `${el._text}${el._text && kids ? " " : ""}${kids}`;
    },
    set textContent(val) {
      children.length = 0;
      el._text = String(val ?? "");
    },
    _html: "",
    get innerHTML() { return el._html; },
    set innerHTML(html) {
      el._html = String(html ?? "");
      children.length = 0;
      el._text = "";
      // Stack-based parse: element children register for id/class queries,
      // text between tags lands on the innermost open element.
      const voids = new Set(["input", "br", "img", "hr", "line", "polyline", "circle", "rect", "path"]);
      const stack = [el];
      const re = /<(\/?)([a-zA-Z0-9-]+)([^>]*?)>|([^<]+)/g;
      let m;
      while ((m = re.exec(el._html)) !== null) {
        const [, close, tag, attrText, text] = m;
        const current = stack[stack.length - 1];
        if (text !== undefined) {
          current._text += text;
          continue;
        }
        if (close) {
          if (stack.length > 1) stack.pop();
          continue;
        }
        const child = createMockElement(tag, ownerDocument);
        const idMatch = attrText.match(/\bid="([^"]+)"/);
        if (idMatch) child.id = idMatch[1];
        const classMatch = attrText.match(/\bclass="([^"]+)"/);
        if (classMatch) child.className = classMatch[1];
        current.appendChild(child);
        const selfClosing = attrText.trimEnd().endsWith("/") || voids.has(tag.toLowerCase());
        if (!selfClosing) stack.push(child);
      }
    },
    setAttribute(name, value) {
      attrs.set(String(name).toLowerCase(), String(value));
      if (String(name).toLowerCase() === "id") el.id = String(value);
      if (String(name).toLowerCase() === "class") el.className = String(value);
    },
    getAttribute(name) { return attrs.get(String(name).toLowerCase()) ?? null; },
    hasAttribute(name) { return attrs.has(String(name).toLowerCase()); },
    appendChild(child) {
      if (child.parentNode) child.parentNode.removeChild(child);
      child.parentNode = el;
      children.push(child);
      return child;
    },
    prepend(child) {
      if (child.parentNode) child.parentNode.removeChild(child);
      child.parentNode = el;
      children.unshift(child);
      return child;
    },
    removeChild(child) {
      const idx = children.indexOf(child);
      if (idx !== -1) { children.splice(idx, 1); child.parentNode = null; }
      return child;
    },
    remove() { if (el.parentNode) el.parentNode.removeChild(el); },
    addEventListener(type, fn) {
      if (!listeners.has(type)) listeners.set(type, new Set());
      listeners.get(type).add(fn);
    },
    removeEventListener(type, fn) { listeners.get(type)?.delete(fn); },
    matches(selector) {
      if (selector.startsWith(".")) return el.classList.contains(selector.slice(1));
      if (selector.startsWith("#")) return el.id === selector.slice(1);
      return el.tagName === selector.toUpperCase();
    },
    querySelector(selector) { return el.querySelectorAll(selector)[0] ?? null; },
    querySelectorAll(selector) {
      const out = [];
      const walk = (node) => {
        for (const c of node.children) {
          if (c.matches(selector)) out.push(c);
          walk(c);
        }
      };
      walk(el);
      return out;
    },
  };
  return el;
}

function createMockDocument() {
  const doc = {
    activeElement: null,
    createElement(tag) { return createMockElement(tag, doc); },
    querySelector() { return null; },
    addEventListener() {},
    removeEventListener() {},
  };
  doc.body = createMockElement("body", doc);
  return doc;
}

const vendorViewUrl = new URL("../../src/page/vendor/view.js", import.meta.url);
const vendorView = await import(vendorViewUrl.href);

const callbacks = {
  onSubmitUrl: () => {},
  onCancel: () => {},
  onReset: () => {},
  onRetrySameUrl: () => {},
  onSave: () => {},
};

function renderJob() {
  const doc = createMockDocument();
  const container = createMockElement("div", doc);
  const state = { status: "downloading", seq: 2, sessionId: "s1", imageCount: 1, transport: "browser-session" };
  const ctx = {
    currentProgress: { current: 1, total: 4 },
    jobActivity: { url: "https://museum.example/art", startedAt: Date.now() - 3000, stepLabel: "Saving image tiles…" },
  };
  vendorView.renderView(container, state, callbacks, ctx);
  return container.querySelector(".dz-card");
}

test("extension job card carries the website geometry", () => {
  const card = renderJob();
  assert.ok(card, "card mounted");
  const job = card.querySelector(".dz-job-section");
  assert.ok(job, "job section mounted");
  assert.equal(card.querySelector("#dz-job-step-text").textContent, "Saving image tiles…");
  assert.equal(card.querySelector("#dz-job-transport").textContent, "Browser session");
  assert.equal(card.querySelector("#dz-job-percent").textContent, "25%");
  assert.equal(card.querySelector("#dz-job-bar").style.width, "25%");
  assert.equal(card.querySelector("#dz-job-track").getAttribute("aria-valuenow"), "25");
  const cancel = card.querySelector("#dz-btn-cancel");
  assert.ok(cancel, "cancel action mounted");
  assert.ok(cancel.classList.contains("dz-btn-secondary"), "cancel uses the shared secondary geometry");
});

test("extension completion reads saved with the file name, no second save click", () => {
  const doc = createMockDocument();
  const container = createMockElement("div", doc);
  vendorView.renderView(
    container,
    { status: "completed", seq: 3, sessionId: "s1", imageCount: 1, transport: "browser-session" },
    callbacks,
    {
      completedInfo: { width: 512, height: 512, mime: "image/png" },
      savedOutput: { name: "dezoomify-512x512.png", width: 512, height: 512, doneTiles: 4, totalTiles: 4, failedTiles: 0 },
    },
  );
  const card = container.querySelector(".dz-card");
  const section = card.querySelector(".dz-completed-section");
  assert.ok(section, "completed section mounted");
  assert.equal(section.querySelector(".dz-completed-title").textContent, "Saved");
  assert.ok(section.querySelector(".dz-completed-summary").textContent.includes("dezoomify-512x512.png"));
  assert.ok(section.querySelector(".dz-completed-summary").textContent.includes("512x512"));
  assert.equal(section.querySelector("#dz-btn-save"), null, "no second-click save button after the anchor fired");
  assert.ok(section.querySelector("#dz-btn-another"), "scan-again action mounted");
  assert.ok(section.querySelector(".dz-actions-row"), "actions row hosts the handoff button slot");
});

test("extension partial completion names its missing tiles honestly", () => {
  const doc = createMockDocument();
  const container = createMockElement("div", doc);
  vendorView.renderView(
    container,
    { status: "completed", seq: 3, sessionId: "s1", imageCount: 1, transport: "browser-session" },
    callbacks,
    {
      completedInfo: { width: 512, height: 512, mime: "image/png" },
      savedOutput: { name: "dezoomify-512x512.png", width: 512, height: 512, doneTiles: 3, totalTiles: 4, failedTiles: 1 },
    },
  );
  const section = container.querySelector(".dz-card").querySelector(".dz-completed-section");
  assert.equal(section.querySelector(".dz-completed-title").textContent, "Saved with gaps");
  assert.match(section.querySelector(".dz-completed-summary").textContent, /3 of 4 tiles/);
});
