name: release-build
on:
  workflow_dispatch:
    inputs:
      plan:
        required: true
        type: string
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: cargo xtask release build --plan ${{ inputs.plan }}
